---
- name: add ssh key
  hosts: "{{ hosts }}"
  become: yes
  gather_facts: true
  tasks:

  - name: Debug Environment Variables
    debug:
      msg: "'{{ lookup('env','AUTHORIZED_KEY') }}' is the 'AUTHORIZED_KEY' environment variable from environment variable section."
      msg: "'{{ lookup('env','USER') }}' is the 'USER' environment variable from environment variable section."

  - name: install public keys
    ansible.posix.authorized_key:
      user: "{{ lookup('env','USER') }}"
      state: present
      validate_certs: False
      key: "{{ lookup('env', 'AUTHORIZED_KEY') }}"
      path: /home/{{ lookup('env','USER') }}/.ssh/authorized_keys
  
  - name: change sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s

  - name: Disable Password Authentication
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: "PasswordAuthentication no"
      state: present
      backup: yes
      validate: sshd -t -f %s
      
  - name: Disable Root Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
      - restart ssh
  
  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted