---
- name: add ssh key
  hosts: "{{ hosts }}"
  become: yes
  tasks:

  - name: install public keys
    ansible.posix.authorized_key:
      user: "{{ lookup('env','USER') }}"
      state: present
      key: "{{ lookup('env', 'AUTHORIZED_KEY') }}"
      path: /home/{{ lookup('env','USER') }}/.ssh/authorized_keys
  
  - name: change sudoers file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s

  - name: Disable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
     notify:
       - restart ssh
  
  handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted