---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Upgrade system packages
  apt:
    upgrade: full
  when: ansible_os_family == "Debian"

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone | default('UTC') }}"

- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined