---
version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE={{ vault_mysql_db }}
      - MYSQL_USER={{ vault_mysql_user }}
      - MYSQL_PASSWORD={{ vault_mysql_password }}
    networks:
      - homelab
    restart: unless-stopped
  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:v2.10.35
    user: "${UID}:${GID}"
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER={{ vault_mysql_user }}
      - SEMAPHORE_DB_PASS={{ vault_mysql_password }}
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT={{ vault_mysql_db_port }}
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB={{ vault_mysql_db }}
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD={{ vault_semaphore_admin_password }}
      - SEMAPHORE_ADMIN_NAME={{ vault_semaphore_admin_name }}
      - SEMAPHORE_ADMIN_EMAIL={{ vault_semaphore_admin_email }}
      - SEMAPHORE_ADMIN={{ vault_semaphore_admin }}
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION={{ vault_semaphore_access_key }}
      - ANSIBLE_HOST_KEY_CHECKING=false
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - homelab
volumes:
  semaphore-mysql:
networks:
  homelab:
    external: true
