- name: Create MySQL container
  community.docker.docker_container:
    name: mysql
    hostname: mysql
    image: mysql:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/mysql/config:/etc/mysql/conf.d"
      - "{{ data_dir }}/mysql/database:/var/lib/mysql"
      - "{{ data_dir }}/mysql/dbbackups:/var/backups/mysql"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "3306:3306"
    networks:
      - name: homelab